issued_contract = {"cpid": "ocds-t1s2t3-MD-1652879244220", "ocid": "ocds-t1s2t3-MD-1652879244220-AC-1652879488470",
                   "planning": {"budget": {"description": "desc of budget UPDATE", "budgetBreakdown": [
                       {"id": "ocds-t1s2t3-MD-1652879205632-FS-1652879219762",
                        "amount": {"amount": 1000.00, "currency": "MDL"},
                        "classifications": {"type": "advance", "relatedItem": "2f59bc90-4009-4cdc-9123-d7d79edb6dbb",
                                            "relatedFinance": "ocds-t1s2t3-MD-1652879205632-FS-1652879219762",
                                            "durationInDays": 20}}], "finance": [
                       {"id": "ocds-t1s2t3-MD-1652879205632-FS-1652879219762",
                        "value": {"amount": 1000.00, "currency": "MDL"}}]}}, "contracts": [
        {"id": "fe03c08f-e00a-4eb3-b0e0-b55d43d1cf8a", "title": "title of AC UPDATE",
         "description": "desc of AC UPDATE", "status": "pending", "statusDetails": "contractPreparation",
         "date": "2022-05-18T13:11:27Z", "awardId": "6ff5ceb4-6fdd-47ea-93ff-04240f212c7a",
         "value": {"amount": 400.00, "amountNet": 300.00, "valueAddedTaxIncluded": True, "currency": "MDL"},
         "period": {"startDate": "2022-05-28T05:58:20Z", "endDate": "2022-05-30T05:58:20Z"}, "documents": [
            {"id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244", "documentType": "contractNotice",
             "title": "contract doc 1 UPDATE", "description": "desc of contract doc 1 UPDATE",
             "relatedLots": ["71c2e6cf-37d2-4aef-a698-d2de11caff8b"]}]}], "tender": {
        "classification": {"id": "18500000-4", "scheme": "CPV", "description": "Bijuterii, ceasuri şi articole conexe"},
        "procurementMethod": "selective", "procurementMethodDetails": "designContest",
        "mainProcurementCategory": "goods", "lots": [
            {"id": "71c2e6cf-37d2-4aef-a698-d2de11caff8b", "internalId": "1-1", "title": "lot 1",
             "description": "first lot", "placeOfPerformance": {"description": "description of locality",
                                                                "address": {"streetAddress": "Lesnaya",
                                                                            "postalCode": "100200", "addressDetails": {
                                                                        "country": {"id": "MD",
                                                                                    "description": "Moldova, Republica",
                                                                                    "scheme": "iso-alpha2",
                                                                                    "uri": "https://www.iso.org"},
                                                                        "region": {"id": "6700000",
                                                                                   "description": "Rezina",
                                                                                   "scheme": "CUATM",
                                                                                   "uri": "http://statistica.md"},
                                                                        "locality": {"id": "6701002",
                                                                                     "description": "s.Ciorna",
                                                                                     "scheme": "CUATM",
                                                                                     "uri": "http://statistica.md"}}}}}],
        "id": "71b9379a-ff3e-4660-b36e-5b62238a738b"}, "awards": [{"id": "6ff5ceb4-6fdd-47ea-93ff-04240f212c7a",
                                                                   "value": {"amount": 400.00, "amountNet": 300.00,
                                                                             "valueAddedTaxIncluded": True,
                                                                             "currency": "MDL"}, "relatedLots": [
            "71c2e6cf-37d2-4aef-a698-d2de11caff8b"], "suppliers": [{"id": "UZ-KTUT-8-000", "name": "siia"}],
                                                                   "documents": [{
                                                                                     "id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244",
                                                                                     "documentType": "shortlistedFirms",
                                                                                     "title": "award doc 1 UPD",
                                                                                     "description": "description of award doc 1 UPD",
                                                                                     "relatedLots": [
                                                                                         "71c2e6cf-37d2-4aef-a698-d2de11caff8b"]}],
                                                                   "items": [
                                                                       {"id": "2f59bc90-4009-4cdc-9123-d7d79edb6dbb",
                                                                        "internalId": "1",
                                                                        "classification": {"id": "18500000-4",
                                                                                           "scheme": "CPV",
                                                                                           "description": "Bijuterii, ceasuri şi articole conexe"},
                                                                        "additionalClassifications": [
                                                                            {"id": "CA18-4", "scheme": "CPVS",
                                                                             "description": "Fără OMG"}],
                                                                        "quantity": 1000.000, "unit": {"id": "238",
                                                                                                       "name": "Gigacalorie pe ora",
                                                                                                       "value": {
                                                                                                           "amount": 10.00,
                                                                                                           "amountNet": 5.00,
                                                                                                           "valueAddedTaxIncluded": True,
                                                                                                           "currency": "MDL"}},
                                                                        "description": "1",
                                                                        "relatedLot": "71c2e6cf-37d2-4aef-a698-d2de11caff8b",
                                                                        "deliveryAddress": {
                                                                            "streetAddress": "item street",
                                                                            "postalCode": "item postalCode",
                                                                            "addressDetails": {
                                                                                "country": {"scheme": "iso-alpha2",
                                                                                            "id": "MD",
                                                                                            "description": "Moldova, Republica",
                                                                                            "uri": "https://www.iso.org"},
                                                                                "region": {"scheme": "CUATM",
                                                                                           "id": "8500000",
                                                                                           "description": "Ştefan Vodă",
                                                                                           "uri": "http://statistica.md"},
                                                                                "locality": {"scheme": "CUATM",
                                                                                             "id": "8511000",
                                                                                             "description": "s.Antoneşti (r-l Ştefan Vodă)",
                                                                                             "uri": "http://statistica.md"}}}},
                                                                       {"id": "a18aa35e-db8b-41f4-a97c-c815d4dbcbf4",
                                                                        "internalId": "1-3",
                                                                        "classification": {"id": "18500000-4",
                                                                                           "scheme": "CPV",
                                                                                           "description": "Bijuterii, ceasuri şi articole conexe"},
                                                                        "additionalClassifications": [
                                                                            {"id": "CA18-4", "scheme": "CPVS",
                                                                             "description": "Fără OMG"}],
                                                                        "quantity": 2000.000,
                                                                        "unit": {"id": "305", "name": "Curie"},
                                                                        "description": "item",
                                                                        "relatedLot": "71c2e6cf-37d2-4aef-a698-d2de11caff8b"}]}],
                   "token": "591cd009-258b-4c69-bc18-07e462f9a758", "owner": "445f6851-c908-407d-9b45-14b92f3e964b",
                   "relatedProcesses": [
                       {"id": "b847a42e-3e76-472c-88ac-4b9426cf69ec", "relationship": ["parent"], "scheme": "ocid",
                        "identifier": "ocds-t1s2t3-MD-1652879244218",
                        "uri": "http://dev.public.eprocurement.systems/tenders/ocds-t1s2t3-MD-1652879244218/ocds-t1s2t3-MD-1652879244218"},
                       {"id": "f3b2d34a-90f7-466b-84a8-e11fcbcbbc06", "relationship": ["x_evaluation"],
                        "scheme": "ocid", "identifier": "ocds-t1s2t3-MD-1652879244218-NP-1652879296295",
                        "uri": "http://dev.public.eprocurement.systems/tenders/ocds-t1s2t3-MD-1652879244218/ocds-t1s2t3-MD-1652879244218-NP-1652879296295"}],
                   "parties": [{"id": "UZ-KTUT-8-000", "name": "siia",
                                "identifier": {"id": "8-000", "legalName": "FOP siia222", "scheme": "UZ-KTUT",
                                               "uri": "siia.uri"},
                                "additionalIdentifiers": [{"id": "1", "legalName": "1", "scheme": "1", "uri": "1"},
                                                          {"id": "1", "legalName": "legal of splr UPD",
                                                           "scheme": "MD UPD", "uri": "splr.com UPD"}],
                                "address": {"streetAddress": "Lumumbi", "postalCode": "10060", "addressDetails": {
                                    "country": {"id": "MD", "description": "Moldova, Republica", "scheme": "iso-alpha2",
                                                "uri": "https://www.iso.org"},
                                    "region": {"id": "8300000", "description": "Şoldăneşti", "scheme": "CUATM",
                                               "uri": "http://statistica.md"},
                                    "locality": {"id": "8311000", "description": "s.Chipeşca", "scheme": "CUATM",
                                                 "uri": "http://statistica.md"}}},
                                "contactPoint": {"name": "Nastya", "email": "nanamarkova@gmail.com",
                                                 "telephone": "0987896788", "faxNumber": "0635330195",
                                                 "url": "nastya.url"}, "persones": [
                           {"title": "Mr.", "id": "MD-IDNO-22-333", "name": "Twister",
                            "identifier": {"scheme": "MD-IDNO", "id": "22-333", "uri": "persona.uri"},
                            "businessFunctions": [{"id": "1", "type": "authority", "jobTitle": "boss",
                                                   "period": {"startDate": "2020-12-10T00:00:00Z"}, "documents": [
                                    {"id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244",
                                     "documentType": "regulatoryDocument", "title": "regDoc",
                                     "description": "regulatory"}]}]},
                           {"title": "Mrs.", "id": "MD-IDNO-1-1", "name": "person 1 UPD",
                            "identifier": {"scheme": "MD-IDNO", "id": "1-1", "uri": "person1.com UPD"},
                            "businessFunctions": [{"id": "5af84ac5-e593-4119-b500-cf886bee68d4", "type": "contactPoint",
                                                   "jobTitle": "job title of person1 UPD",
                                                   "period": {"startDate": "2022-05-10T05:58:20Z"}, "documents": [
                                    {"id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244",
                                     "documentType": "regulatoryDocument", "title": "title of business doc1 UPD",
                                     "description": "desc of business doc1 UPD"}]}]}],
                                "details": {"typeOfSupplier": "individual", "mainEconomicActivities": [
                                    {"id": "1-1", "scheme": "MD-MD", "description": "MEA", "uri": "mea.uri"},
                                    {"id": "1", "scheme": "MD-CAEM", "description": "desc of mea UPD",
                                     "uri": "mea.com UPD"}], "scale": "large", "permits": [
                                    {"id": "22-22", "scheme": "MD-IDNO", "url": "permit.uri",
                                     "permitDetails": {"issuedBy": {"id": "MD-IDNO-44-55", "name": "Ira"},
                                                       "issuedThought": {"id": "MD-IDNO-44-66", "name": "Taras"},
                                                       "validityPeriod": {"startDate": "2020-12-08T09:40:25Z",
                                                                          "endDate": "2020-12-08T09:40:27Z"}}},
                                    {"id": "prmt1", "scheme": "MD", "url": "prmt1.com UPD",
                                     "permitDetails": {"issuedBy": {"id": "1", "name": "name of issuedBy UPD"},
                                                       "issuedThought": {"id": "2",
                                                                         "name": "name of issuedThought UPD"},
                                                       "validityPeriod": {"startDate": "2022-06-21T05:58:20Z",
                                                                          "endDate": "2022-06-23T05:58:20Z"}}}],
                                            "bankAccounts": [{"description": "bank bank", "bankName": "monobank",
                                                              "address": {"streetAddress": "Gorkogo",
                                                                          "postalCode": "10070", "addressDetails": {
                                                                      "country": {"id": "MD",
                                                                                  "description": "Moldova, Republica",
                                                                                  "scheme": "iso-alpha2",
                                                                                  "uri": "https://www.iso.org"},
                                                                      "region": {"id": "3400000",
                                                                                 "description": "Donduşeni",
                                                                                 "scheme": "CUATM",
                                                                                 "uri": "http://statistica.md"},
                                                                      "locality": {"id": "3426000",
                                                                                   "description": "s.Sudarca",
                                                                                   "scheme": "CUATM",
                                                                                   "uri": "http://statistica.md"}}},
                                                              "identifier": {"scheme": "UA-MFO", "id": "88-99"},
                                                              "accountIdentification": {"scheme": "IBAN",
                                                                                        "id": "UA213223130000026007233566001"},
                                                              "additionalAccountIdentifiers": [
                                                                  {"scheme": "fiscal", "id": "55-999"}]},
                                                             {"description": "privat description UPD",
                                                              "bankName": "privat bank UPD", "address": {
                                                                 "streetAddress": "streetAddress of privat bank UPD",
                                                                 "postalCode": "postalCode of privat bank UPD",
                                                                 "addressDetails": {"country": {"id": "MD",
                                                                                                "description": "Moldova, Republica",
                                                                                                "scheme": "iso-alpha2",
                                                                                                "uri": "https://www.iso.org"},
                                                                                    "region": {"id": "5300000",
                                                                                               "description": "Hînceşti",
                                                                                               "scheme": "CUATM",
                                                                                               "uri": "http://statistica.md"},
                                                                                    "locality": {"id": "5315000",
                                                                                                 "description": "s.Buţeni",
                                                                                                 "scheme": "CUATM",
                                                                                                 "uri": "http://statistica.md"}}},
                                                              "identifier": {"scheme": "UA-MFO", "id": "1"},
                                                              "accountIdentification": {"scheme": "IBAN", "id": "2"},
                                                              "additionalAccountIdentifiers": [
                                                                  {"scheme": "fiscal", "id": "3"}]}],
                                            "legalForm": {"scheme": "MD-CFOJ", "id": "11-111",
                                                          "description": "description of legalForm UPD",
                                                          "uri": "legalForm.com UPD"}}, "roles": ["supplier", "payee"]},
                               {"id": "MD-IDNO-BYR", "name": "EI BUYER NAME",
                                "identifier": {"id": "BYR", "legalName": "LLC EI Buyer", "scheme": "MD-IDNO"},
                                "additionalIdentifiers": [
                                    {"id": "2", "legalName": "legalName of buyer1", "scheme": "MD-IDNO",
                                     "uri": "buyer1.com"}], "address": {"streetAddress": "Metrologichna",
                                                                        "addressDetails": {"country": {"id": "MD",
                                                                                                       "description": "Moldova, Republica",
                                                                                                       "scheme": "iso-alpha2",
                                                                                                       "uri": "https://www.iso.org"},
                                                                                           "region": {"id": "9800000",
                                                                                                      "description": "UATSN",
                                                                                                      "scheme": "CUATM",
                                                                                                      "uri": "http://statistica.md"},
                                                                                           "locality": {"id": "9804000",
                                                                                                        "description": "or.Dnestrovsc",
                                                                                                        "scheme": "CUATM",
                                                                                                        "uri": "http://statistica.md"}}},
                                "contactPoint": {"name": "contPoint name", "email": "contPoint mail",
                                                 "telephone": "contPoint phone"}, "persones": [
                                   {"title": "Mr.", "id": "MD-IDNO-2", "name": "person2",
                                    "identifier": {"scheme": "MD-IDNO", "id": "2", "uri": "person2.com"},
                                    "businessFunctions": [
                                        {"id": "21af5086-7acb-44ba-b7d0-3e012fe79eef", "type": "chairman",
                                         "jobTitle": "job title of person2",
                                         "period": {"startDate": "2022-04-21T05:58:20Z"}, "documents": [
                                            {"id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244",
                                             "documentType": "regulatoryDocument", "title": "title of business doc2",
                                             "description": "description of business doc2"}]}]}],
                                "details": {"typeOfBuyer": "BODY_PUBLIC", "mainGeneralActivity": "DEFENCE",
                                            "mainSectoralActivity": "AIRPORT_RELATED_ACTIVITIES", "bankAccounts": [
                                        {"description": "description of monobank", "bankName": "monobank",
                                         "address": {"streetAddress": "streetAddress of monobank",
                                                     "postalCode": "postalCode of monobank", "addressDetails": {
                                                 "country": {"id": "MD", "description": "Moldova, Republica",
                                                             "scheme": "iso-alpha2", "uri": "https://www.iso.org"},
                                                 "region": {"id": "9800000", "description": "UATSN", "scheme": "CUATM",
                                                            "uri": "http://statistica.md"},
                                                 "locality": {"id": "9802000", "description": "or.Camenca (UATSN)",
                                                              "scheme": "CUATM", "uri": "http://statistica.md"}}},
                                         "identifier": {"scheme": "UA-MFO", "id": "4"},
                                         "accountIdentification": {"scheme": "IBAN", "id": "5"},
                                         "additionalAccountIdentifiers": [{"scheme": "fiscal", "id": "6"}]}],
                                            "legalForm": {"scheme": "MD-CFOJ", "id": "2",
                                                          "description": "description of legalForm2",
                                                          "uri": "legalForm2.com"}}, "roles": ["buyer"]}]}

issued_contract_no_buyer = {"cpid": "ocds-t1s2t3-MD-1652879244220", "ocid": "ocds-t1s2t3-MD-1652879244220-AC-1652879488470",
                   "planning": {"budget": {"description": "desc of budget UPDATE", "budgetBreakdown": [
                       {"id": "ocds-t1s2t3-MD-1652879205632-FS-1652879219762",
                        "amount": {"amount": 1000.00, "currency": "MDL"},
                        "classifications": {"type": "advance", "relatedItem": "2f59bc90-4009-4cdc-9123-d7d79edb6dbb",
                                            "relatedFinance": "ocds-t1s2t3-MD-1652879205632-FS-1652879219762",
                                            "durationInDays": 20}}], "finance": [
                       {"id": "ocds-t1s2t3-MD-1652879205632-FS-1652879219762",
                        "value": {"amount": 1000.00, "currency": "MDL"}}]}}, "contracts": [
        {"id": "fe03c08f-e00a-4eb3-b0e0-b55d43d1cf8a", "title": "title of AC UPDATE",
         "description": "desc of AC UPDATE", "status": "pending", "statusDetails": "contractPreparation",
         "date": "2022-05-18T13:11:27Z", "awardId": "6ff5ceb4-6fdd-47ea-93ff-04240f212c7a",
         "value": {"amount": 400.00, "amountNet": 300.00, "valueAddedTaxIncluded": True, "currency": "MDL"},
         "period": {"startDate": "2022-05-28T05:58:20Z", "endDate": "2022-05-30T05:58:20Z"}, "documents": [
            {"id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244", "documentType": "contractNotice",
             "title": "contract doc 1 UPDATE", "description": "desc of contract doc 1 UPDATE",
             "relatedLots": ["71c2e6cf-37d2-4aef-a698-d2de11caff8b"]}]}], "tender": {
        "classification": {"id": "18500000-4", "scheme": "CPV", "description": "Bijuterii, ceasuri şi articole conexe"},
        "procurementMethod": "selective", "procurementMethodDetails": "designContest",
        "mainProcurementCategory": "goods", "lots": [
            {"id": "71c2e6cf-37d2-4aef-a698-d2de11caff8b", "internalId": "1-1", "title": "lot 1",
             "description": "first lot", "placeOfPerformance": {"description": "description of locality",
                                                                "address": {"streetAddress": "Lesnaya",
                                                                            "postalCode": "100200", "addressDetails": {
                                                                        "country": {"id": "MD",
                                                                                    "description": "Moldova, Republica",
                                                                                    "scheme": "iso-alpha2",
                                                                                    "uri": "https://www.iso.org"},
                                                                        "region": {"id": "6700000",
                                                                                   "description": "Rezina",
                                                                                   "scheme": "CUATM",
                                                                                   "uri": "http://statistica.md"},
                                                                        "locality": {"id": "6701002",
                                                                                     "description": "s.Ciorna",
                                                                                     "scheme": "CUATM",
                                                                                     "uri": "http://statistica.md"}}}}}],
        "id": "71b9379a-ff3e-4660-b36e-5b62238a738b"}, "awards": [{"id": "6ff5ceb4-6fdd-47ea-93ff-04240f212c7a",
                                                                   "value": {"amount": 400.00, "amountNet": 300.00,
                                                                             "valueAddedTaxIncluded": True,
                                                                             "currency": "MDL"}, "relatedLots": [
            "71c2e6cf-37d2-4aef-a698-d2de11caff8b"], "suppliers": [{"id": "UZ-KTUT-8-000", "name": "siia"}],
                                                                   "documents": [{
                                                                                     "id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244",
                                                                                     "documentType": "shortlistedFirms",
                                                                                     "title": "award doc 1 UPD",
                                                                                     "description": "description of award doc 1 UPD",
                                                                                     "relatedLots": [
                                                                                         "71c2e6cf-37d2-4aef-a698-d2de11caff8b"]}],
                                                                   "items": [
                                                                       {"id": "2f59bc90-4009-4cdc-9123-d7d79edb6dbb",
                                                                        "internalId": "1",
                                                                        "classification": {"id": "18500000-4",
                                                                                           "scheme": "CPV",
                                                                                           "description": "Bijuterii, ceasuri şi articole conexe"},
                                                                        "additionalClassifications": [
                                                                            {"id": "CA18-4", "scheme": "CPVS",
                                                                             "description": "Fără OMG"}],
                                                                        "quantity": 1000.000, "unit": {"id": "238",
                                                                                                       "name": "Gigacalorie pe ora",
                                                                                                       "value": {
                                                                                                           "amount": 10.00,
                                                                                                           "amountNet": 5.00,
                                                                                                           "valueAddedTaxIncluded": True,
                                                                                                           "currency": "MDL"}},
                                                                        "description": "1",
                                                                        "relatedLot": "71c2e6cf-37d2-4aef-a698-d2de11caff8b",
                                                                        "deliveryAddress": {
                                                                            "streetAddress": "item street",
                                                                            "postalCode": "item postalCode",
                                                                            "addressDetails": {
                                                                                "country": {"scheme": "iso-alpha2",
                                                                                            "id": "MD",
                                                                                            "description": "Moldova, Republica",
                                                                                            "uri": "https://www.iso.org"},
                                                                                "region": {"scheme": "CUATM",
                                                                                           "id": "8500000",
                                                                                           "description": "Ştefan Vodă",
                                                                                           "uri": "http://statistica.md"},
                                                                                "locality": {"scheme": "CUATM",
                                                                                             "id": "8511000",
                                                                                             "description": "s.Antoneşti (r-l Ştefan Vodă)",
                                                                                             "uri": "http://statistica.md"}}}},
                                                                       {"id": "a18aa35e-db8b-41f4-a97c-c815d4dbcbf4",
                                                                        "internalId": "1-3",
                                                                        "classification": {"id": "18500000-4",
                                                                                           "scheme": "CPV",
                                                                                           "description": "Bijuterii, ceasuri şi articole conexe"},
                                                                        "additionalClassifications": [
                                                                            {"id": "CA18-4", "scheme": "CPVS",
                                                                             "description": "Fără OMG"}],
                                                                        "quantity": 2000.000,
                                                                        "unit": {"id": "305", "name": "Curie"},
                                                                        "description": "item",
                                                                        "relatedLot": "71c2e6cf-37d2-4aef-a698-d2de11caff8b"}]}],
                   "token": "591cd009-258b-4c69-bc18-07e462f9a758", "owner": "445f6851-c908-407d-9b45-14b92f3e964b",
                   "relatedProcesses": [
                       {"id": "b847a42e-3e76-472c-88ac-4b9426cf69ec", "relationship": ["parent"], "scheme": "ocid",
                        "identifier": "ocds-t1s2t3-MD-1652879244218",
                        "uri": "http://dev.public.eprocurement.systems/tenders/ocds-t1s2t3-MD-1652879244218/ocds-t1s2t3-MD-1652879244218"},
                       {"id": "f3b2d34a-90f7-466b-84a8-e11fcbcbbc06", "relationship": ["x_evaluation"],
                        "scheme": "ocid", "identifier": "ocds-t1s2t3-MD-1652879244218-NP-1652879296295",
                        "uri": "http://dev.public.eprocurement.systems/tenders/ocds-t1s2t3-MD-1652879244218/ocds-t1s2t3-MD-1652879244218-NP-1652879296295"}],
                   "parties": [{"id": "UZ-KTUT-8-000", "name": "siia",
                                "identifier": {"id": "8-000", "legalName": "FOP siia222", "scheme": "UZ-KTUT",
                                               "uri": "siia.uri"},
                                "additionalIdentifiers": [{"id": "1", "legalName": "1", "scheme": "1", "uri": "1"},
                                                          {"id": "1", "legalName": "legal of splr UPD",
                                                           "scheme": "MD UPD", "uri": "splr.com UPD"}],
                                "address": {"streetAddress": "Lumumbi", "postalCode": "10060", "addressDetails": {
                                    "country": {"id": "MD", "description": "Moldova, Republica", "scheme": "iso-alpha2",
                                                "uri": "https://www.iso.org"},
                                    "region": {"id": "8300000", "description": "Şoldăneşti", "scheme": "CUATM",
                                               "uri": "http://statistica.md"},
                                    "locality": {"id": "8311000", "description": "s.Chipeşca", "scheme": "CUATM",
                                                 "uri": "http://statistica.md"}}},
                                "contactPoint": {"name": "Nastya", "email": "nanamarkova@gmail.com",
                                                 "telephone": "0987896788", "faxNumber": "0635330195",
                                                 "url": "nastya.url"}, "persones": [
                           {"title": "Mr.", "id": "MD-IDNO-22-333", "name": "Twister",
                            "identifier": {"scheme": "MD-IDNO", "id": "22-333", "uri": "persona.uri"},
                            "businessFunctions": [{"id": "1", "type": "authority", "jobTitle": "boss",
                                                   "period": {"startDate": "2020-12-10T00:00:00Z"}, "documents": [
                                    {"id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244",
                                     "documentType": "regulatoryDocument", "title": "regDoc",
                                     "description": "regulatory"}]}]},
                           {"title": "Mrs.", "id": "MD-IDNO-1-1", "name": "person 1 UPD",
                            "identifier": {"scheme": "MD-IDNO", "id": "1-1", "uri": "person1.com UPD"},
                            "businessFunctions": [{"id": "5af84ac5-e593-4119-b500-cf886bee68d4", "type": "contactPoint",
                                                   "jobTitle": "job title of person1 UPD",
                                                   "period": {"startDate": "2022-05-10T05:58:20Z"}, "documents": [
                                    {"id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244",
                                     "documentType": "regulatoryDocument", "title": "title of business doc1 UPD",
                                     "description": "desc of business doc1 UPD"}]}]}],
                                "details": {"typeOfSupplier": "individual", "mainEconomicActivities": [
                                    {"id": "1-1", "scheme": "MD-MD", "description": "MEA", "uri": "mea.uri"},
                                    {"id": "1", "scheme": "MD-CAEM", "description": "desc of mea UPD",
                                     "uri": "mea.com UPD"}], "scale": "large", "permits": [
                                    {"id": "22-22", "scheme": "MD-IDNO", "url": "permit.uri",
                                     "permitDetails": {"issuedBy": {"id": "MD-IDNO-44-55", "name": "Ira"},
                                                       "issuedThought": {"id": "MD-IDNO-44-66", "name": "Taras"},
                                                       "validityPeriod": {"startDate": "2020-12-08T09:40:25Z",
                                                                          "endDate": "2020-12-08T09:40:27Z"}}},
                                    {"id": "prmt1", "scheme": "MD", "url": "prmt1.com UPD",
                                     "permitDetails": {"issuedBy": {"id": "1", "name": "name of issuedBy UPD"},
                                                       "issuedThought": {"id": "2",
                                                                         "name": "name of issuedThought UPD"},
                                                       "validityPeriod": {"startDate": "2022-06-21T05:58:20Z",
                                                                          "endDate": "2022-06-23T05:58:20Z"}}}],
                                            "bankAccounts": [{"description": "bank bank", "bankName": "monobank",
                                                              "address": {"streetAddress": "Gorkogo",
                                                                          "postalCode": "10070", "addressDetails": {
                                                                      "country": {"id": "MD",
                                                                                  "description": "Moldova, Republica",
                                                                                  "scheme": "iso-alpha2",
                                                                                  "uri": "https://www.iso.org"},
                                                                      "region": {"id": "3400000",
                                                                                 "description": "Donduşeni",
                                                                                 "scheme": "CUATM",
                                                                                 "uri": "http://statistica.md"},
                                                                      "locality": {"id": "3426000",
                                                                                   "description": "s.Sudarca",
                                                                                   "scheme": "CUATM",
                                                                                   "uri": "http://statistica.md"}}},
                                                              "identifier": {"scheme": "UA-MFO", "id": "88-99"},
                                                              "accountIdentification": {"scheme": "IBAN",
                                                                                        "id": "UA213223130000026007233566001"},
                                                              "additionalAccountIdentifiers": [
                                                                  {"scheme": "fiscal", "id": "55-999"}]},
                                                             {"description": "privat description UPD",
                                                              "bankName": "privat bank UPD", "address": {
                                                                 "streetAddress": "streetAddress of privat bank UPD",
                                                                 "postalCode": "postalCode of privat bank UPD",
                                                                 "addressDetails": {"country": {"id": "MD",
                                                                                                "description": "Moldova, Republica",
                                                                                                "scheme": "iso-alpha2",
                                                                                                "uri": "https://www.iso.org"},
                                                                                    "region": {"id": "5300000",
                                                                                               "description": "Hînceşti",
                                                                                               "scheme": "CUATM",
                                                                                               "uri": "http://statistica.md"},
                                                                                    "locality": {"id": "5315000",
                                                                                                 "description": "s.Buţeni",
                                                                                                 "scheme": "CUATM",
                                                                                                 "uri": "http://statistica.md"}}},
                                                              "identifier": {"scheme": "UA-MFO", "id": "1"},
                                                              "accountIdentification": {"scheme": "IBAN", "id": "2"},
                                                              "additionalAccountIdentifiers": [
                                                                  {"scheme": "fiscal", "id": "3"}]}],
                                            "legalForm": {"scheme": "MD-CFOJ", "id": "11-111",
                                                          "description": "description of legalForm UPD",
                                                          "uri": "legalForm.com UPD"}}, "roles": ["supplier", "payee"]},
                               {"id": "MD-IDNO-BYR", "name": "EI BUYER NAME",
                                "identifier": {"id": "BYR", "legalName": "LLC EI Buyer", "scheme": "MD-IDNO"},
                                "additionalIdentifiers": [
                                    {"id": "2", "legalName": "legalName of buyer1", "scheme": "MD-IDNO",
                                     "uri": "buyer1.com"}], "address": {"streetAddress": "Metrologichna",
                                                                        "addressDetails": {"country": {"id": "MD",
                                                                                                       "description": "Moldova, Republica",
                                                                                                       "scheme": "iso-alpha2",
                                                                                                       "uri": "https://www.iso.org"},
                                                                                           "region": {"id": "9800000",
                                                                                                      "description": "UATSN",
                                                                                                      "scheme": "CUATM",
                                                                                                      "uri": "http://statistica.md"},
                                                                                           "locality": {"id": "9804000",
                                                                                                        "description": "or.Dnestrovsc",
                                                                                                        "scheme": "CUATM",
                                                                                                        "uri": "http://statistica.md"}}},
                                "contactPoint": {"name": "contPoint name", "email": "contPoint mail",
                                                 "telephone": "contPoint phone"}, "persones": [
                                   {"title": "Mr.", "id": "MD-IDNO-2", "name": "person2",
                                    "identifier": {"scheme": "MD-IDNO", "id": "2", "uri": "person2.com"},
                                    "businessFunctions": [
                                        {"id": "21af5086-7acb-44ba-b7d0-3e012fe79eef", "type": "chairman",
                                         "jobTitle": "job title of person2",
                                         "period": {"startDate": "2022-04-21T05:58:20Z"}, "documents": [
                                            {"id": "3cc535fe-3471-445e-a5d2-73971c7c39ee-1652261467244",
                                             "documentType": "regulatoryDocument", "title": "title of business doc2",
                                             "description": "description of business doc2"}]}]}],
                                "details": {"typeOfBuyer": "BODY_PUBLIC", "mainGeneralActivity": "DEFENCE",
                                            "mainSectoralActivity": "AIRPORT_RELATED_ACTIVITIES", "bankAccounts": [
                                        {"description": "description of monobank", "bankName": "monobank",
                                         "address": {"streetAddress": "streetAddress of monobank",
                                                     "postalCode": "postalCode of monobank", "addressDetails": {
                                                 "country": {"id": "MD", "description": "Moldova, Republica",
                                                             "scheme": "iso-alpha2", "uri": "https://www.iso.org"},
                                                 "region": {"id": "9800000", "description": "UATSN", "scheme": "CUATM",
                                                            "uri": "http://statistica.md"},
                                                 "locality": {"id": "9802000", "description": "or.Camenca (UATSN)",
                                                              "scheme": "CUATM", "uri": "http://statistica.md"}}},
                                         "identifier": {"scheme": "UA-MFO", "id": "4"},
                                         "accountIdentification": {"scheme": "IBAN", "id": "5"},
                                         "additionalAccountIdentifiers": [{"scheme": "fiscal", "id": "6"}]}],
                                            "legalForm": {"scheme": "MD-CFOJ", "id": "2",
                                                          "description": "description of legalForm2",
                                                          "uri": "legalForm2.com"}}, "roles": ["procuringEntity"]}]}